language: python
cache: pip
dist: bionic
python:
- '3.7'
- '3.8'
- '3.9'
install:
- pip install poetry
- poetry install --no-root
script:
- poetry run python utils/download_protobufs.py
- poetry install
- poetry run pytest --spec
before_deploy:
- poetry build
deploy:
- provider: script
  skip_existing: true
  skip_cleanup: true
  script: poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
  on:
    repo: cetanu/envoy_data_plane
    branch: master
    python: '3.9'
env:
  global:
  - secure: PhgWVU0zPcsVDEN2TIq8Q90je20W7B1yGNdCbUY5rS7FVd1KcEppGXzCi4IJQhmkQ4ke1ZH92iukF5aC4Qk9LMmqNEL2FnN6ihLGWRDMWuxGFp+hcvGL3ZOGmxquN7zXXsxpC9k7pOR2uccNZ3k/QnqlRd4a7Ay0WgZOnGHsZUTTzLqFRQBu7cjfgE1b1WWMLdBCU7R+aY2jOO0hmi6li0wJYsIEjbNN+CGPL36/piPdjPjIq6akRy/PbbnMglJaGPyj3nlu/9WLf5x6bVSckpG5dFR6nbGpEBOEDaMXwyo+8OFeY0Fdlyi+6G584qUppqoGFrsCC1T9yYHO9zN2VnzAM9rNxmFLFwgAuyhV+LQQok9j12xvGUil+685CEVizYmuwDLy+jn0CMac3bYSD1CRM79eDGde3MlMAZE1Wo5dcExSKqzRRWTGvsvCmOmA+0Q0TSxByYj0ylwbJcjzmGX+ty6L9LUob4xzz2V1VL2xQXlpK96QG7iQiR8iuNM4MT3cSI2WslZiifJPNhttk3T1kx6rzp0QulTx3HH8LgGRttP/0McUWudY6CwNNK+7sl/IyTwvfxcJP570scnNr0xp8tcvLcyTfNC2LZGl/3d7P4WysRc75bM1qrF3phpSd/En8nVxDfkMp04SIGsbSlNaqqYX0IscvQ592ab0Wh0=
  - secure: bJpDCnvf7HFx/VEvh6r69zyTNOC1tery2DCLqcNM1uHXyiJw65Mfv1EO88e3CE6/djrEZz0nsn8qrZfiNeqBjxkbwtws92EQx1SyrHEqaG5SyGZEG0RM4zYkqmEGPce9pOElUWtyO8v/gcPzA6AmkFgeRdQHUjQaAnszx1bUPLHSlu/Lq0aGqTsYvleB9/gtxlbEOKqvimDGOYruW29RuhU588ruDrtlK2R+czCu1LMlUbvLc57lJ1v6jLcTfF7QlADmBHw9h/8keiPooJWJqrbz9wY5bGMHd7Jvcug08rBZGFNd1Qjilx8ICSOZqYcqQopj5h4uYDhxcKw0+Pe9KlA//5qMxwe3+DW7OvAXf87yDkniPHq3n0IcMKpytSn2Bwapu9MxHQWetXbBOyCeQk+Bc6rbv+7W4+PVbsHl5Ks+hh04DkIMmlHAY47nnjrC2uHH7jL/ZkTqZWKR4UqtTWkOK2XmuWZ+Oj5u0J8HQ5EAluWfenBYY7rQb14c+BVvqg6yn8iLH1/UGsi7NywFcvxHdxc3SrA/4LHCbkzwD5V0d7WjPlx7LBhGua4J5vlTd7ZAtxDJr2QWc+w+sBf0YR/4/sN+Rf1SD8CWM5DvrNWYYavKMJUjd3Af7Gp2cggZc7/b8dHMybsW1BitwmCfmWhzfMTDPwoBvIqX3r6GtCo=
